"""HTTP client for Schwab Market Data Production API — read-only by construction.

Safety contract enforced here:
  * Base URL is pinned to `/marketdata/v1/`. Any caller passing a path that
    would escape that namespace raises `ScopeViolation`. There is no method
    that accepts an absolute URL.
  * Only GET is exposed. There is no `post`, `put`, `patch`, or `delete`.
  * The Trader API (`/trader/v1/`) is never imported, referenced, or routed
    to from anywhere in this package.

If you need to extend this to the Trader API, do not edit this file —
create a separate package. Keeping the scope split at the module boundary
makes the read-only guarantee auditable.
"""

from __future__ import annotations

import os
from typing import Any

import httpx

from mcp_schwab import auth

SCHWAB_MARKETDATA_BASE = "https://api.schwabapi.com/marketdata/v1"


class ScopeViolation(RuntimeError):
    """Raised when a caller tries to leave the market-data namespace."""


class SchwabAuthError(RuntimeError):
    """Raised when credentials are missing or refresh fails."""


def _validate_path(path: str) -> str:
    if path.startswith("http://") or path.startswith("https://"):
        raise ScopeViolation(
            "Absolute URLs are not permitted; pass a path relative to "
            "the market-data base."
        )
    clean = "/" + path.lstrip("/")
    # Reject anything that even looks like trader scope.
    forbidden_fragments = ("/trader/", "/accounts/", "/orders", "/transactions")
    lowered = clean.lower()
    for fragment in forbidden_fragments:
        if fragment in lowered:
            raise ScopeViolation(
                f"Path {clean!r} touches forbidden scope fragment {fragment!r}. "
                "This MCP is read-only market data."
            )
    return clean


class SchwabMarketDataClient:
    """Minimal async GET-only client. Refreshes its own access token."""

    def __init__(
        self,
        *,
        client_id: str | None = None,
        client_secret: str | None = None,
        tokens: auth.TokenSet | None = None,
        http: httpx.AsyncClient | None = None,
    ) -> None:
        self._client_id = client_id or os.environ.get("SCHWAB_APP_KEY")
        self._client_secret = client_secret or os.environ.get("SCHWAB_APP_SECRET")
        self._tokens = tokens
        self._http = http or httpx.AsyncClient(timeout=30.0)
        if not self._client_id or not self._client_secret:
            raise SchwabAuthError(
                "SCHWAB_APP_KEY and SCHWAB_APP_SECRET must be set in the "
                "environment (or passed explicitly) before the client can run."
            )

    async def aclose(self) -> None:
        await self._http.aclose()

    async def __aenter__(self) -> "SchwabMarketDataClient":
        return self

    async def __aexit__(self, *_exc: object) -> None:
        await self.aclose()

    def _ensure_tokens(self) -> auth.TokenSet:
        tokens = self._tokens or auth.load_tokens()
        if tokens is None:
            raise SchwabAuthError(
                "No Schwab tokens on disk. Run `python -m mcp_schwab.cli "
                "authorize` once to bootstrap."
            )
        if tokens.is_expired():
            tokens = auth.refresh_access_token(
                client_id=self._client_id,  # type: ignore[arg-type]
                client_secret=self._client_secret,  # type: ignore[arg-type]
                refresh_token=tokens.refresh_token,
            )
            auth.save_tokens(tokens)
        self._tokens = tokens
        return tokens

    async def get(self, path: str, params: dict[str, Any] | None = None) -> Any:
        clean_path = _validate_path(path)
        tokens = self._ensure_tokens()
        url = SCHWAB_MARKETDATA_BASE + clean_path
        response = await self._http.get(
            url,
            params=params,
            headers={"Authorization": f"Bearer {tokens.access_token}"},
        )
        if response.status_code == 401:
            # Token may have been revoked between our skew check and now.
            tokens = auth.refresh_access_token(
                client_id=self._client_id,  # type: ignore[arg-type]
                client_secret=self._client_secret,  # type: ignore[arg-type]
                refresh_token=tokens.refresh_token,
            )
            auth.save_tokens(tokens)
            self._tokens = tokens
            response = await self._http.get(
                url,
                params=params,
                headers={"Authorization": f"Bearer {tokens.access_token}"},
            )
        response.raise_for_status()
        return response.json()
